server {
    listen 80;
    listen [::]:80;
    server_name wodeff.cn;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name wodeff.cn;

    ssl_certificate /etc/letsencrypt/live/wodeff.cn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wodeff.cn/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    include /etc/nginx/snippets/enterprise-kb-graph-webhook.locations.conf;

    location / {
        return 404;
    }
}
